#!/bin/sh

## SPDX-FileCopyrightText: 2004 - 2022 Tim Pope <https://tpo.pe>
## SPDX-FileCopyrightText: 2023 Qusal contributors
##
## SPDX-License-Identifier: GPL-3.0-or-later

## Credits: https://github.com/tpope/dotfiles/blob/master/.lessfilter

set -eu

if test -d "$1"; then
  exec ls -lF "$1"
else
  case $1 in
    *.json) command -v jq >/dev/null && exec jq -C . "$1";;
  esac
fi

exit 1
