# SPDX-FileCopyrightText: 2023 Benjamin Grande M. S. <ben.grande.b@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
skip_list:
  - 205  # use '.sls' as a Salt State file extension
severity: true
