#!/bin/sh

# SPDX-FileCopyrightText: 2022 - 2023 unman <unman@thirdeyesecurity.org>
# SPDX-FileCopyrightText: 2023 Benjamin Grande M. S. <ben.grande.b@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

set -eu

nft insert rule ip qubes custom-forward tcp dport 53 drop
nft insert rule ip qubes custom-forward udp dport 53 drop

## TODO: Is this working?
handle="$(nft -a list table qubes |
    awk 'BEGIN{c0} /related,established/{c++; if (c==1) print $NF}')"

nft add rule ip qubes custom-input position "$handle" iifname "vif*" tcp dport 53 accept
nft add rule ip qubes custom-input position "$handle" iifname "vif*" udp dport 53 accept
