#!/bin/sh
set -eu

# shellcheck disable=SC1090
. ~/git-shell-commands/.git-shell-lib

# shellcheck disable=SC2154
if command -v tree >/dev/null; then
  tree -L 1 "$base"
else
  find "$base" -maxdepth 1 -type d
fi
