#!/bin/sh

## SPDX-FileCopyrightText: 2023 Qusal contributors
##
## SPDX-License-Identifier: GPL-3.0-or-later

set -eu

# shellcheck disable=SC1090
. ~/git-shell-commands/.git-shell-lib

# shellcheck disable=SC2154
if command -v tree >/dev/null; then
  tree -L 1 "$base"
else
  find "$base" -maxdepth 1 -type d
fi
