#!/bin/sh

## SPDX-FileCopyrightText: 2023 Qusal contributors
##
## SPDX-License-Identifier: GPL-3.0-or-later

# shellcheck disable=SC1090,1091

. "$HOME/.profile"
case $- in *i*) . "$HOME/.bashrc";; esac
