#!/usr/bin/env zsh
## Zsh does not source /etc/profile as it is not a Bourne based Shell, but
## some distributions such as Qubes, Whonix, Debian, Gentoo ship files to
## /etc/profile.d.

emulate sh -c "source /etc/profile"
. "$HOME/.profile"
