#!/usr/bin/env zsh

## SPDX-FileCopyrightText: 2023 Qusal contributors
##
## SPDX-License-Identifier: GPL-3.0-or-later

if test -z "$ENV" && test -n "$PATH"; then
  case $- in
    *l*) ;;
      *) . "$HOME/.zprofile" >/dev/null ;;
  esac
fi
